### PR TITLE
NXBT-2706: add pgsql 11

### PR DESCRIPTION
**Pull request by ffjdm**

### CODE REVIEW

**Comment by pabgrall** [comment]
:+1:

**Comment by mguillaume** [comment]
👎
I'm not opposed to the change per se, but as far as I can tell we have no job testing pgsql 11, whatever the doc says, so I'm a bit dubious about packaging it in the installer.

**Comment by ffjdm** [comment]
Please check again with fguillaume. PG11 is tested.

**Comment by tmartins** [comment]
:+1:

**Pull request merged**
